# AnyKernel3 Ramdisk Mod Script
# For Kokuban Kernel Weekly Patcher (Dynamic Menu Final Version)
properties() { '
kernel.string=Kokuban Kernel S24 Weekly Patch Kit by YuzakiKokuban
do.devicecheck=1
do.modules=0
do.systemless=1
do.cleanup=1
do.cleanuponabort=0
device.name1=e3q
device.name2=e2q
device.name3=e1q
device.name4=q6q
device.name5=b6q
'; }

block=/dev/block/bootdevice/by-name/boot;
is_slot_device=0;
ramdisk_compression=auto;
patch_vbmeta_flag=auto;

. tools/ak3-core.sh;
dump_boot;

# --- Dynamic UI Selection ---
ui_print " "
ui_print "**********************************************"
ui_print "* Kokuban · 周常更新差分包"
ui_print "**********************************************"
ui_print " "

# Read the base kernel name from the file generated by build script
if [ -f "base_kernel_name" ]; then
  BASE_NAME=$(cat base_kernel_name)
else
  BASE_NAME="LKM" # Fallback
fi

# Dynamically build the menu based on available patches
VARIANT_LIST=("$BASE_NAME (基础版, 默认)")
PATCH_FILES=()
for p in bs_patches/*.p; do
    [ -e "$p" ] || continue
    variant=$(basename "$p" .p)
    variant_upper=$(echo "$variant" | tr '[:lower:]' '[:upper:]' | sed 's/SUKI SUULTRA/SukiSUU/')
    VARIANT_LIST+=("$variant_upper (内置 $variant_upper)")
    PATCH_FILES+=("$variant")
done

# Only show menu if there are choices
if [ ${#VARIANT_LIST[@]} -gt 1 ]; then
  ui_print "请选择您要刷入的内核版本:"
  ui_print "   (使用音量键选择, 电源键确认)"
  ui_print " "
  SEL_INDEX=$(select_menu "${VARIANT_LIST[@]}")
else
  ui_print "检测到只有一个内核版本，将直接刷入。"
  SEL_INDEX=0
fi

if [ "$SEL_INDEX" == "0" ]; then
  CHOICE="$BASE_NAME"
  ui_print "  > 您选择了: $BASE_NAME (基础版)"
else
  CHOICE="${PATCH_FILES[$((SEL_INDEX - 1))]}"
  CHOICE_UPPER=$(echo "$CHOICE" | tr '[:lower:]' '[:upper:]' | sed 's/SUKI SUULTRA/SukiSUU/')
  ui_print "  > 您选择了: $CHOICE_UPPER"
fi

# --- Patching Logic ---
if [ "$CHOICE" != "$BASE_NAME" ]; then
  ui_print "  > 正在应用 ${CHOICE_UPPER} 补丁..."
  ./tools/bspatch Image Image_patched "bs_patches/${CHOICE}.p"
  if [ $? -eq 0 ]; then
    ui_print "  > 补丁应用成功！"
    mv -f Image_patched Image
  else
    ui_print "  > 错误：补丁应用失败！将刷入基础版。"
  fi
else
  ui_print "  > 正在刷入基础版 ($BASE_NAME) 内核..."
fi

write_boot;
